version: '2'

volumes:
  pgdata:
  redisdata:

services:
  web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
          - .:/code
      ports:
          - "8000:8000"
      env_file: .env
      links:
        - postgres
        - redis

  postgres:
      restart: always
      image: postgres:latest
      ports:
        - "5432:5433"
      volumes:
        - pgdata:/var/lib/postgresql/data/

  redis:
      restart: always
      image: redis:latest
      ports:
        - "6379:6379"
      volumes:
        - redisdata:/data


